#cloud-config

apt_update: true
apt_upgrade: true
packages:
  - cowsay
  - python-pip
  - python-dev
  - build-essential
  - octave

byobu_default: system

write_files:
  - path: /home/ubuntu/cowsay-app.py
    content: |
      from flask import Flask, jsonify
      import subprocess
      import sys
      app = Flask(_name_)
      @app.route('/cowsay/api/v1.0/saysomething', methods=['GET'])
      def cow_say():
        data=subprocess.check_output(["cowsay","Hello student"])
        return data
        if _name_ == '_main_':
          app.run(host='0.0.0.0',debug=True)

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install -y docker-ce
  - git clone https://github.com/oliback/ACC2-BENCHOP.git
  