#cloud-config

users:
	- name: first
	  groups : sudo
	  shell: /bin/bash
	  sudo: ['ALL=(ALL) NOPASSWD:ALL']

#	- name: second
#	  groups: sudo
#	  shell: /bin/bash
#	  sudo: ['ALL=(ALL) NOPASSWD:ALL']
#	  expiredate: 2017-10-20

#	- name: third
#	  shell: /bin/bash
#	  sudo: ['ALL=(ALL) NOPASSWD:ALL']
#	  expiredate: 2017-10-20


# groups:
#	- kukilainen: [third]

# chpasswd:
#	list: |
#		first:sagbab
#		second:qahbabab
#		third:sarsari
#	expire: False

write_files:
	- path: /test.txt
	- content: |
		Here is a line.
		Another line is here.
	- owner: first:sudo

package_upgrade: true

package_update: true

packages:
	- python-pip
	- lxc
	- docker
	- octave
	
# ssh_authorized_keys:
#	- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfmP2i2nCalFR120oq1EVYaQFuHHrz97u3ExXviLCPa3fRhF3ZQ/LmqznYxaE3wtBIK0Ta5dGBE1cPHT+2ZU0xr5u1b8UjtAfs1iwMr7r2MJBEFCAzCfcEIruKGK1KDZRDGRXV+eRTQG9CJ4g4bQSdkDKm/Om9B3eYYuJRIbid6xwGn826rYTGnlQrPgJe2TA+w4E7OkeAaf6u/mH8ljNugczQRjM6rbPQ5typ6bmfWZoYNdrj3QMnoYr2gZZGkC1otVV/RgwWpyiZylbWF5TI1NnUKh6pFZPsf84pB5mkqcbmBltQaK2m5SipFgUWs2SX/nTvtGsNecWCWJM9sfsn ubuntu@haubir-lab-3-dont-delete

# ssh_keys:

# ca-certs:

# manage-resolv-conf: true
# resolv_conf:
#	nameservers:
#		- 'first_nameserver'
#		- 'second_nameserver'
#	searchdomains:
#		- first.domain.com
#		- second.domain.com
#	domain: domain.com
#	options:
#		option1: value1
#		option2: value2
#		option3: value3

runcmd:
	- touch /test.txt
	- echo "quzalqort"
	- pip install --upgrade pip
	- pip install flask 
	- pip install celery 
	- pip install rabbitmq
	- cat test.txt

# power_state:
#	timeout: 1000
#	delay: "+30"
#	message: Rebooting in 30 minutes. Save important work.
#	mode: reboot


